[package]
name = "data-source"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.25"
tar = { version = "0.4.43", optional = true }
reqwest = { version = "0.12", optional = true, features = ["blocking"] }
thiserror = "2.0.11"

[features]
default = ["tar", "reqwest"]
